### ISSUE TITLE
Blank page after installing plugin version 4.4.4

### ISSUE THREAD

**Issue by iljalukin** [igniterealtime/openfire-fastpath-plugin#13]
After installing the plugin version 4.4.4 and clicking on the Fastpath menu button to get into its settings a blank page is shown. The browser network tab shows HTTP code 404, while getting plugins/fastpath/workgroup-summary.jsp. What could be the problem? 
The plugin version 4.4.3 shows settings, but throws an exception while clicking on workgroup edit button.

**Comment by deleolajide** [comment]
What version of openfire are you running?

![image](https://user-images.githubusercontent.com/110731/65247098-b2963600-dae7-11e9-99df-fef65a086b34.png)

**Comment by iljalukin** [comment]
4.4.1, I'm using docker image from gizmotronic: https://hub.docker.com/r/gizmotronic/openfire/

**Comment by iljalukin** [comment]
Just tried out the 4.4.0 docker image, works well. Seems that 4.4.1 does some curious things.

**Comment by deleolajide** [comment]
It was compiled with openfire 4.3 in order to support Openfire 4.3.2 which is still in wide use. Looks like 4.4.1 will need a new build. My dev platform is still on 4.4.0

**Comment by iljalukin** [comment]
> 4.4.1, I'm using docker image from gizmotronic: https://hub.docker.com/r/gizmotronic/openfire/

Oops, I was occidentally using the plugin version 4.4.3 with Openfire 4.4.0. After updating the plugin to 4.4.4 it's the same blank page as with Openfire 4.4.1, even after a clean install.

**Comment by deleolajide** [comment]
I was able to reproduce by deleting my local build and adding the plugin from the admin web console. Reopening Maven build issue.

![image](https://user-images.githubusercontent.com/110731/65264078-bfc21d80-db05-11e9-9712-382bb69a851d.png)

**Comment by iljalukin** [comment]
I have placed the file [web.xml](https://github.com/guusdk/openfire-clientControl-plugin/blob/3f72b7b578f66a2b118a428d5c490825b63d13ae/src/web/WEB-INF/web.xml) in src/web/WEB-INF folder of plugin source and started the build locally with mvn clean package. After installing the plugin from jar file there was finally no more blank page.

**Comment by deleolajide** [comment]
For anyone else, please use the jar file [here](https://github.com/igniterealtime/openfire-fastpath-plugin/releases/tag/v4.4.4)

**Comment by wrooot** [comment]
Will it be replaced on the site?

**Comment by deleolajide** [comment]
No. That wont happen until issue #13 is fixed. It looks like it might just be a simple case of adding the missing web.xml file. I can do that next time I work on the fastpath plugin.
