### ISSUE TITLE
How to use FastPath

### ISSUE THREAD

**Issue by albertusgeyser** [igniterealtime/openfire-fastpath-plugin#26]
Good Day

Could anyone explain how they use FastPath on their own websites to get clients to connect to FastPath as it was done years ago?

Thank You

Albertus Geyser

**Comment by akrherz** [comment]
This is an issue tracker for software bugs and not general help.  Please see our [community forums](https://discourse.igniterealtime.org/).

**Comment by deleolajide** [comment]
> Could anyone explain how they use FastPath on their own websites

Try to read the [readme file](https://github.com/igniterealtime/openfire-fastpath-plugin#fastpath-plugin-readme) from top to bottom

**Comment by albertusgeyser** [comment]
Good Day 

Sorry for asking here, but do not get answers from ignite community.
@deleolajide could you see if you could help me on following:

https://discourse.igniterealtime.org/t/webclients-chat-api/85727/5

Thank You

Albertus Geyser
