### ISSUE TITLE
Add Dispatcher that offer to all agents at once

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-fastpath-plugin#42]
The Round Robin dispatcher dispatches an offer to the first available agent, waits for it to respond, then goes on to the next one.

An alternative approach should be added, one in which an offer goes out to all available agents, where the first one to respond would 'win'.

**Comment by deleolajide** [comment]
The [work-groups XEP](https://xmpp.org/extensions/xep-0142.html#proto-agent-offer) does not specify how an agent should be offered. That implies it is up to the implementation to decide. I would prefer ALL Agents to be the default. It would give a better customer/visitor experience.

The Admin UI does not show any way to change or configure dispatchers. We might have to provide that or just use a system property edit at the first implementation.
